#:schema node_modules/wrangler/config-schema.json
name = "aia"
main = "worker.ts"
account_id = "fa73541af4fcdd947ab78c12fe990a34"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Automatic Build Command for Worker CI/CD
[build]
command = "npm run build"

# Serve Frontend SPA Assets directly in Workers
[assets]
directory = "dist"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"

# 1. Cloudflare D1 SQL Database Binding
[[d1_databases]]
binding = "ROOH_D1_DATABASE"
database_name = "h"
database_id = "8480585e-443f-4ef9-b4e4-45c941c9dbf1"

# 2. Cloudflare KV Namespace Binding
[[kv_namespaces]]
binding = "ROOH_KV_CACHE"
id = "6d9110610f2c45b09c15d3f2f5dee50a"

# 3. Cloudflare R2 Bucket Binding
[[r2_buckets]]
binding = "ROOH_STORAGE_R2"
bucket_name = "roohme"

# Environment Variables & Admin Credentials
[vars]
ADMIN_EMAIL = "roohpro1@gmail.com"
ENVIRONMENT = "production"
BASE_DOMAIN = "https://roohpro.com"
APP_BASE_PATH = "/ai"
